### ISSUE TITLE
Decide on license

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka-workshop-slides#1]
Before we upload the slides and the cheat sheet we should decide on a license for this repository. My apologies for being late with this but I haven't thought of this until now. Thoughts? @bussmann @psychocoderHPC @sbastrakov

**Comment by psychocoderHPC** [comment]
Code examples should be the same license we have for alpaka examples.
IMO slides should have cc-by or how it is called. The free version where you must link author.


Rene

Am 28. Juni 2020 17:49:03 MESZ schrieb Jan Stephan <notifications@github.com>:

**Comment by sbastrakov** [comment]
I agree with @psychocoderHPC . However, the code examples are not for tomorrow, right? Tomorrow is just use standard alpaka, build and run standard vectorAdd?

**Comment by j-stephan** [comment]
Yes, there won't be any code tomorrow (apart from compiling the standard vectorAdd from alpaka). This is just for the actual slides and the cheat sheet. The "new" examples will be placed in a separate repository

**Comment by bussmann** [comment]
Agreed on @psychocoderHPC 's choice.

**Comment by ax3l** [comment]
> IMO slides should have cc-by or how it is called. The free version where you must link author.

CC-BY-4.0 - good choice https://creativecommons.org/licenses/by/4.0/

Good luck and have fun at the workshop! :crossed_fingers:

**Comment by j-stephan** [comment]
Do we want to use the SA attribute? This ensures that the license stays the same. Together this would be the CC-BY-SA 4.0 license.

https://creativecommons.org/licenses/by-sa/4.0/deed.en

**Comment by bussmann** [comment]
Yes

**Comment by j-stephan** [comment]
License added.
