### ISSUE TITLE
Small typo in brach name on workshop slide

### ISSUE THREAD

**Issue by KseniaBastrakova** [alpaka-group/alpaka-workshop-slides#2]
On slide 2, there is typo: branch "release-0.5.0" istead of "0.5.0"
https://github.com/alpaka-group/alpaka-workshop-slides/blob/200629_cern/00_getting_started/04_installation.pdf

**Comment by sbastrakov** [comment]
Note: it's not a typo, but the branch was called `release-0.5.0` at the time of the workshop, but it was a pre-release and the actual release got later called just `0.5.0`. Still, I think this needs to be updated on the slides so that future readers are not confused.
