### ISSUE TITLE
Typo in Day_2/13

### ISSUE THREAD

**Issue by chillenzer** [alpaka-group/alpaka-workshop-slides#61]
@franzpoeschel I think you meant `ccmake .` and not `cmake .` in line 7 of https://github.com/alpaka-group/alpaka-workshop-slides/edit/oct2024_workshop/Day_2/13_streaming_io_solution/build/buildAndRun.md.

**Comment by franzpoeschel** [comment]
That error is already in `Day_1/0_helloIndex/build`, I added only the "Hint for LUMI" part
